### ISSUE TITLE
Mobs in the searing gorge and slag pits run away when a friendly dies

### ISSUE THREAD

**Issue by jamedawg00** [elysium-project/server#3218] opened 2017-10-16 00:14 UTC
Yeah so questing in searing gorge and i been killing packs of dwarves and once a smelly little dwarf dies his stinky little friends run away as if they have low health and are fleeing... but dont have low health they r just fleeing when a friend dies for like 4 seconds then come back. def not normal.

**Comment by Terranzin** [comment] 2017-11-14 20:24
I´ve now reviewed your issue, the issue is rather hard to find solid proof except when it comes to the War Golems.

- Heavy War Golem (Id: 5854) is actually immune to any fear effect but still flees, _not_ correct.
- Above does not happen to "Tempered War Golem" (Id:5853) - _correct_

Regarding the Dark Iron dwarfs there´s a uneven pattern.

The following Dark Iron dwarfs flees:
- Dark Iron Lookout (Id: 8566)
- Dark Iron Slaver (Id: 5844)
- Dark Iron Taskmaster (Id: 5846)

The following Dark Iron dwarfs does not flee:
- Dark Iron Geologist (Id: 5839)
- Dark Iron Watchman (Id: 8637)
- Dark Iron Steamsmith (Id: 5840)

There´s a couple of videos back from vanilla where you can easily see that these mobs does not flee when their fellow Dark Iron dies, though lacking the solid proof of video with a date. Also the Dark Iron dwarfs are lacking the emote that usually is displayed once a mob does tend to flee.

**Comment by Terranzin** [comment] 2017-11-15 21:43
Closing this issue and moving it to our new bug-tracker. Please follow it here: https://github.com/elysium-project/bug-tracker/issues/33

**Closed by Terranzin** 2017-11-15 21:43 UTC
