### ISSUE TITLE
Quest: In Search of Thaelrid level Requirement too high

### ISSUE THREAD

**Issue by femdead** [elysium-project/server#1162] opened 2017-06-26 11:35 UTC
Quest level is wrong. It is currently lvl 20+ and should be 18+.
http://www.wowhead.com/quest=1198/in-search-of-thaelrid
https://vanilla-twinhead.twinstar.cz/?issue=6508
If you look at the next quest in the chain, Blackfathom Villainy, it is level 18+. Horde can pick up Blackfathom Villainy at lvl 18 and obtain the wand. This is important for twinks. 
quest id: 1198

**Comment by some2** [comment] 2017-06-26 13:53
Partialy duplicate of https://elysium-project.org/bugtracker/issue/2491 (with source)

Min. level 18 seems to be correct

**Comment by femdead** [comment] 2017-06-26 18:22
They don't seem to check the bug tracker

**Closed** 2017-06-29 07:05 UTC
