### ISSUE TITLE
Darkmooncard: Blue Dragon not proccing from all spells

### ISSUE THREAD

**Issue by ItsmeAga** [elysium-project/server#1966] opened 2017-08-06 22:50 UTC
The Card should proc from all spells having a manacost. Tested with renew in 30min and not a single proc.
Thats a sample size of ~1200 casts. Lots of earlier reports that have been closed/("fixed"), refer to those for more detailed information.

**Comment by Dalleren** [comment] 2017-08-07 11:12
I think it does not proc if you do not enter combat from casting your spells.

**Comment by ItsmeAga** [comment] 2017-08-07 13:26
gonna try again in combat, but that would be a weird implementation, on retail it often procced when you did stuff in cities

**Comment by Phoosy** [comment] 2017-08-07 13:36
Reference: https://github.com/elysium-project/server/issues/314

**Comment by ItsmeAga** [comment] 2017-08-07 14:40
Tried renew incombat too, doesnt seem to proc either

**Comment by femdead** [comment] 2017-08-07 16:25
see if it procs on the first successful (aka actually healed something) tick of renew, not just the cast - that is how it has worked on other servers

**Comment by mrulewicz66** [comment] 2017-08-07 16:27
Tested in several scholo and ubrs runs. Not proccing from any instant casts spells, renew/dispel magic. Almost useless atm... mindtap talisman showing much better results.

**Comment by DudeFallen** [comment] 2017-08-08 22:02
I got the Darkmoon Card on my Druid three days ago and it is not working like it was in Vanilla WoW. 

I did some testing out of combat and in combat with different spells. (similar to the testing inside reference #314 linked by Phoosy)

out of combat:
I casted over 300 rejuvenation rank 1 on my self and had 0 procs.
I casted 150 rejuvenation rank 1 on a player in my grp and had 0 procs
I casted over 200 abolish poisen on my self and had 0 procs.
I casted 100 abolish poisen on a player in my grp and had 0 procs
I casted 200 healing touch rank 1 on my self and had 0 procs.
I casted 100 healing touch rank 1 on a player in my grp and had 0 procs.

in combat (Players in Grp tanked an Elite and we stayed infight):
I casted over 300 rejuvenation rank 1 on my self and had 0 procs.
I casted 150 rejuvenation rank 1 on a player in my grp and had 0 procs
I casted over 200 abolish poisen on my self and had 0 procs.
I casted 100 abolish poisen on a player in my grp and had 0 procs
I casted 200 healing touch rank 1 on my self and had 0 procs.
I casted 100 healing touch rank 1 on a player in my grp and had 0 procs.

I also tried max rank spells but had no procs either. 
According to reference #314 it was fixed with the Development Update 24.05.2017 (Quote: "Items: Darkmoon Card: Blue Dragon should now proc correctly").

It would be awesome if you can try to fix this card again so it is the real BIS item it should be :D

Thanks in advance for looking into this bug!

**Comment by ItsmeAga** [comment] 2017-08-09 08:04
I noticed that apparently it procs from Renew ticks, which it shouldnt. Sounds like someone didnt understand how it should work, and fixed it the wrong way

**Comment by TotoBoy** [comment] 2017-08-10 15:53
I got the Darkmoon Card Blue Dragon yesterday on my Druid. I tried the same like DudeFallen did. I got 0 procs, neither with casting healing touch, rejuvenation or abolish poison.
I imagined from the old vanilla days, that this item even procs by casting some alchy stuff. 
So please look after this issue and try to fix it. Everyone would appreciate this for sure.

**Comment by moto1337** [comment] 2017-08-10 16:54
I've also done some Testing with the same results. I would apprechiate a fix as soon as posible.

**Comment by GuybrushGit** [comment] 2017-08-11 00:04
Tested on current dev branch, can't reproduce. Aura procs on renew, healing touch, abolish, etc

**Comment by Maievh** [comment] 2017-08-11 09:59
Is not working on the live Elysium server tho. No procs on Dispel Magic, Abolish, Renew, PW:Shield, any buff spell etc.

Works with: Heal, Greater Heal, Flash Heal, Holy nova

Supposed to work with: anything that costs mana.

**Comment by Mesino** [comment] 2017-08-12 02:55
As stated above it is not correctly working with instants on the Elysium server. Should be working with all spells.

**Comment by coryo** [comment] 2017-08-12 03:29
I just tested the development branch. I can proc Blue Dragon with Renew, Abolish Disease, Power Word: Fortitude. It seems like this has been fixed but not moved to the live server yet.

**Comment by DudeFallen** [comment] 2017-08-12 10:04
Thanks for the reply Coryo! 

Could be that it was only fixed on Anathema server? I also did some further testing and I got it procced via Healing Touch (Rank 1) but not with Abolish Poisen or Rejuvenation. 

Thanks again for your time and support regarding this issue! Really appreciate it!

**Comment by Maievh** [comment] 2017-08-18 04:39
That seems to be the case, its working as intended on Anathema but for some reason Elysium didn't receive the fix. Hope this gets fixed soon.

**Comment by DudeFallen** [comment] 2017-08-26 08:59
Any updates on this topic? Support would be really awesome in fixing this!

**Comment by Frapee** [comment] 2017-09-03 22:56
Would really appreciate an update on this. It seems to work correctly on Anathema but not on elysium.

I managed to trigger the trinket on Healing Touch and the first tick of a rejuvenation but not with anything else like abolish poison or remove curse, which is not a correct behavior. (Elysium)

Thanks in advance.

**Comment by elysiumpriest** [comment] 2017-09-03 23:16
Is this getting fixed anytime soon? It works on the PTR but not on Elysium for some reason.

**Comment by TotoBoy** [comment] 2017-09-06 17:27
I would love if this is getting updated soon.

**Comment by Dalleren** [comment] 2017-09-20 07:57
As of yesterday it procced of all spells on my priest.

**Comment by QAkvastskaft** [comment] 2017-09-20 19:12
Fixed here: https://forum.elysium-project.org/topic/53637-development-update-08092017/

**Closed by QAkvastskaft** 2017-09-20 19:12 UTC
