### ISSUE TITLE
Arcanite Dragongling flame buffets itself

### ISSUE THREAD

**Issue by notpentadactyl** [elysium-project/server#819] opened 2017-05-22 12:08 UTC
See #490, #494 and https://github.com/elysium-project/server/commit/0733f10bc127242a972743337c7ddfc85f5471cf for more informations

Tested it today (22 May) and it is still killing itself, see combat log.

![ad](https://cloud.githubusercontent.com/assets/21175961/26308056/d51f2508-3ef7-11e7-84f7-8591d5fc4243.png)

**Comment by lequintal69** [comment] 2017-05-22 15:35
why are you posting another report of the same issue?

**Comment by strudelkuchen** [comment] 2017-05-22 16:27
> why are you posting another report of the same issue?

according to https://github.com/elysium-project/server/commit/0733f10bc127242a972743337c7ddfc85f5471cf the fix was merged 27 days ago, it would be reasonable to assume (imho) it would be fixed by now. The fix either doesn't work correctly or wasn't applied (even so it got merged).

**Comment by m-laniakea** [comment] 2017-05-23 02:42
@strudelkuchen Just because it was merged, does not mean it's applied to live servers. We have many commits, and it's a long process for QA to go through all of them. The fact that it's noted the in-progress Dev Update should tell you it's been fixed, but has not been put on live servers yet. https://github.com/elysium-project/server/issues/731

Further, this is a duplicate of https://github.com/elysium-project/server/issues/490.

**Closed by m-laniakea** 2017-05-23 02:42 UTC
