### ISSUE TITLE
Smoked desert dumplings Elysium realm

### ISSUE THREAD

**Issue by pel-eili** [elysium-project/server#666] opened 2017-05-10 07:26 UTC
Hello there is chain quest in Silithus started by "Calandrath"   And she is supposed to teach u a cooking recipe at 2nd part of the chain. Upon completing the quest she doesn't teach u the recipe and opens the 3rd quest chain tested with 300 cooking skill.

**Comment by Nelythia** [comment] 2017-05-10 18:58
Not a bug.

It got introduced with the AQ patch.

**Comment by pel-eili** [comment] 2017-05-10 22:09
still a bugbecayse the quest is available

**Comment by Slicy** [comment] 2017-05-15 11:00
It was introduced with 1.8, not AQ patch which is 1.9.

**Comment by GuybrushGit** [comment] 2017-10-03 20:35
Fixed in new progressive database.

**Closed by GuybrushGit** 2017-10-03 20:35 UTC
