### ISSUE TITLE
Hunter's mark displaying on minimap for non-party members. 

### ISSUE THREAD

**Issue by ChristianTucker** [elysium-project/server#977] opened 2017-06-04 16:58 UTC
I haven't tested to see if this occurred across faction, (ie: being able to see if a Horde hunter marks an Alliance player, and being able to see an alliance ally marked by an enemy hunter) however I've noticed several times that marked targets appear on the minimap when they are marked by a hunter of the same faction. 

I only played during the final days of Vanilla before TBC was released, however I don't recall this ever being the case. Earlier today in the starting zone my map was filled with dots from hunters marking different targets while questing. I'm fairly sure it should only show the mark if you're in a party with them.  (Or actually if you're the hunter, and it shouldn't matter otherwise)

**Comment by WobLight** [comment] 2017-06-06 21:39
https://youtu.be/4Pp9Kp1F3KY?t=24

**Comment by Lorilay2** [comment] 2017-06-06 22:11
This was always the case since the dawn of time.

**Comment by WobLight** [comment] 2017-06-07 10:28
Why did you closed it? This is valid and should be closed by Elysium.
Other references:
https://youtu.be/4Pp9Kp1F3KY?t=777
https://youtu.be/HxfN9f88P0I?t=5

Actually, looks like the mark is visible only to the hunter itself
https://youtu.be/HxfN9f88P0I?t=28

**Comment by notpentadactyl** [comment] 2017-06-08 12:52
> This was always the case since the dawn of time.
This is how I remember it as well. Might have been changed in a patch.

**Comment by WobLight** [comment] 2017-06-08 12:55
I can confirm that team could see marks in TBC, they changed it for arenas imo,

**Comment by WobLight** [comment] 2017-06-08 18:19
For anyone still skeptical
https://youtu.be/2bIvcPRkoUI?t=10
https://youtu.be/2bIvcPRkoUI?t=233

**Comment by ChristianTucker** [comment] 2017-06-11 15:17
@WobLight  I have re-opened it. I was testing this on other servers from Vanilla -> WoTLK as it was stated that this wasn't an error. After some testing, I can confirm that the mark is only supposed to be visible to the hunter.

**Comment by taurenrogue** [comment] 2017-06-15 21:56
I'm convinced that there should be no map icon for anyone but the hunter, but there's still no proof that marked target should be invisible to the party...

**Comment by WobLight** [comment] 2017-06-15 21:57
Why? Proof linked just 2 comments above

**Comment by WobLight** [comment] 2017-06-15 22:01
oh wait, you mean invisible when stealthed?

**Comment by taurenrogue** [comment] 2017-06-15 22:04
> oh wait, you mean invisible when stealthed?
Yes of ofc invisible via invis pot/succubus invis / cloaking device :)

**Comment by WobLight** [comment] 2017-06-15 22:07
Honestly it would be near to impossible to prove whatever they should or not, especially considering the poor quality of videos from 10 years ago. I guess that it should follow the same rule the minimap does though.

**Closed** 2017-07-03 08:36 UTC
