### ISSUE TITLE
Lokhtos Darkbargainer in BRD does not sell *Plans: Dark Iron Boots* as he should

### ISSUE THREAD

**Issue by chevas** [elysium-project/server#87] opened 2017-03-21 19:42 UTC
Thorium Brotherhood Rep - A player who is exalted should be able to buy Dark Iron Boots. They are in the game well before the current patch, but the NPC does not have Dark Iron Boots Plans for sale. There are existing players (Lebowski on Anathema Elysium is one of them) that have already learned the plans and currently make the boots. He mentioned that Nano from the original Nostalrius had to fix the same issue for him once he reached exalted with TB.

**Comment by henkethebenke** [comment] 2017-03-22 08:37
On which server? I guess Anathema since Lebowski plays on that server.

**Comment by FractalCabush** [comment] 2017-03-22 11:38
The Plans: Dark Iron Boots are available in patch 1.7 so if you are on anathema then yes it should be added to his vendor items.

**Comment by chevas** [comment] 2017-03-22 15:56
We spoke on Discord, but for Github record:
Anathema on Elysium

Thanks for your response!

**Comment by m-laniakea** [comment] 2017-03-24 20:37
Confirmed by QA, and admin has been notified.

**Comment by chevas** [comment] 2017-04-07 23:21
Any update on this being pushed to production?

**Comment by chevas** [comment] 2017-04-24 16:51
Bump

**Comment by chevas** [comment] 2017-05-21 23:05
How hard is it to add a database entry? I've been waiting for months to have this item added to the vendor.

**Comment by m-laniakea** [comment] 2017-05-22 02:14
@chevas Our admins are very busy. Things like this just get lost sometimes.

**Comment by chevas** [comment] 2017-05-22 14:04
Understood. Apologies for my snide comment.

**Comment by brotalnia** [comment] 2017-05-22 14:21
I submitted a fix for this two months ago, but they denied it, saying it should be added in itemization, even though the plans are sold by the vendor in 1.12, and to my understanding the base database is supposed to be for 1.12 since there are no itemization patches for 1.12. They even have queries to remove it from the vendors in some of the itemization patches, even though it is not there in the default db, which means the queries do nothing. https://github.com/elysium-project/itemization/search?utf8=%E2%9C%93&q=20040&type=

At the same time, they make changes that are not supposed to be in 1.12 as migrations, instead of in the itemization patches, where patch specific changes are supposed to go. https://github.com/elysium-project/server/commit/548dee68edb5bf2afc3b2a66fe4c469c210a2fc4

So i am completely confused as to what is supposed to be in the database and what is not anymore. There needs to be a post explaining what changes are to be made in migrations, and what in itemization, and most importantly what patch is the default database for -> https://github.com/elysium-project/server/releases/tag/02.03.2017

**Comment by chevas** [comment] 2017-05-22 14:26
That seems totally wrong. These boots were added in **Patch 1.7**. These boots have nothing to do with re itemization that came later. As said above, there are players on Anathema who can make these boots and there are numerous players running around with said boots. Regardless of what itemization is planned to happen or is not supposed to happen, the plans for these boots need to be added.

**Comment by m-laniakea** [comment] 2017-05-26 01:23
@brotalnia You are correct, that one belongs in itemization. The reason I denied your commit, was because it would mean it would be applied to Elysium and Zeth'Kur as well. 
I've added your pull request to the next database release, however. 

@chevas Our admins have everything they need to add the item, but it seems the last update caused unforseen issues that need to be taken care of first. When it's added, you'll be the first to know. Sorry about the long wait.

**Comment by nobomehl** [comment] 2017-06-15 07:56
Are the plans available on Anathema yet? Got the same problem on Darrowshire! It's just frustrating paying thousands of gold for Fiery/Lava Core's to get exalted at Thorium Brotherhood just to see that someone forgot to implement the item you've been working on over a month.

**Comment by onalem** [comment] 2017-06-29 10:39
still waiting for the boots on darrowshire...

m-laniakea commented on 26 May 
Our admins have everything they need to add the item, but it seems the last update caused unforseen issues that need to be taken care of first. When it's added, you'll be the first to know. Sorry about the long wait.

they should've been implemented at ZG patch 1.7  2-3 months ago

**Comment by nobomehl** [comment] 2017-07-14 20:55
still waiting for any information for Plans: Dark Iron Boots - are you planning to implement them?              they're missing now for 3 months on Darrowshire

**Comment by JosipbrozElysium** [comment] 2017-08-02 23:24
Taken note. The item will be added to Darrowshire in the upcoming 1.8 patch!

Best regards!

**Comment by chevas** [comment] 2017-08-03 00:53
OK that's good, but did it get added to Anathema???

**Comment by shenna-elysium** [comment] 2017-08-03 16:48
http://db.vanillagaming.org/?npc=12944 is not supposed to sell http://db.vanillagaming.org/?item=20761 until 1.9. Yes for Anathema.

**Comment by nobomehl** [comment] 2017-08-03 21:17
https://www.engadget.com/2011/07/19/wow-archivist-patch-1-7-rise-of-the-blood-god/
under "profession" you'll find: Dark Iron Boots have been added as Blacksmithing plans that require Exalted reputation with the Thorium Brotherhood.

http://wowwiki.wikia.com/wiki/Patch_1.7.0
Dark Iron Boots have been added as Blacksmithing plans that require Exalted reputation with the Thorium Brotherhood. 

http://www.ign.com/boards/threads/wow-players-patch-1-7-notes.250298458/
 Dark Iron Boots have been added as Blacksmithing plans that require
Exalted reputation with the Thorium Brotherhood.

**Comment by nobomehl** [comment] 2017-08-03 21:22
every patch notes list from 1.7 i find states that dark iron boots got added to the game!
no patch notes list from 1.9 i find states anything about dark iron boots.

**Comment by chevas** [comment] 2017-08-03 22:32
No no no, this is still broken. **********Reopen the ticket.************ Do you see Plans for Dark Iron Boots?

![image](https://user-images.githubusercontent.com/57968/28946709-372357ce-7869-11e7-9eb0-c8ce9ca103c9.png)

![image](https://user-images.githubusercontent.com/57968/28946716-3f9597f0-7869-11e7-966e-97b01fc1159d.png)

![image](https://user-images.githubusercontent.com/57968/28946722-46bae7ec-7869-11e7-9d17-179222a96b23.png)

**Comment by JosipbrozElysium** [comment] 2017-08-03 22:40
@chevas When we announce something as fixed (here), this usually means that a fix has been applied on the git repo, not the live servers. 

Best regards!

**Comment by nobomehl** [comment] 2017-08-03 22:44
they're implemented on the 1.8 ptr

**Closed** 2017-08-03 22:44 UTC
Labels: QA Confirmed Issue

**Comment by chevas** [comment] 2017-08-03 22:48
What patch is Anathema currently on? I thought we were 1.10

**Comment by chevas** [comment] 2017-08-05 16:41
Could I get clarity on my above question? Thanks.

**Comment by JosipbrozElysium** [comment] 2017-08-05 18:34
If the ticket has been closed, then please leave the conversation. The issue has been fully resolved. Anathema is 1.10, but you could've checked it yourself easily here: https://elysium-project.org/timeline

**Comment by chevas** [comment] 2017-08-05 21:53
I'd be happy to leave this conversation as long as there is clarity. I am being told that the fix is in the 1.8 PTR, but that makes no sense for Anathema. If Anathema is currently on patch 1.10 (which I knew and assumed), then why isn't the fix already live? I just verified two days ago that the fix is not live. Therefore, if Anathema is on Patch 1.10, that means patch 1.8 should already be live. This is why I was double-checking if we were, in fact, on patch 1.10.

Please explain why this issue is closed, yet Anathema is on Patch 1.10, but there is no fix that is supposedly supposed to have happened all the way back in patch 1.8.

**Comment by JosipbrozElysium** [comment] 2017-08-05 22:46
It should be already on the live server:
https://cdn.discordapp.com/attachments/329842562351235073/343524166169001994/unknown.png

Maybe delete the WDB folder and retry?

**Comment by chevas** [comment] 2017-08-05 22:56
Where did you take that screenshot from? You are outside somewhere. This is the only instance of this particular NPC that I know of:

http://db.vanillagaming.org/?npc=12944#.

He's in the bard in BRD. If there's another copy of him, where?

**Comment by nobomehl** [comment] 2017-09-22 18:16
Dark Iron Boots still not implemented on Darrowshire btw...
