### ISSUE TITLE
[Bonereaver's Edge] proc is bugged

### ISSUE THREAD

**Issue by tellio02** [elysium-project/server#1371] opened 2017-07-06 11:35 UTC
The [Bonereaver's Edge] proc is bugged - each proc is resetting the timer but not stacking the armor debuff.

**Comment by StadenElysium** [comment] 2017-07-06 13:05
Duplicate of https://github.com/elysium-project/server/issues/1363.

**Closed by StadenElysium** 2017-07-06 13:05 UTC
