### ISSUE TITLE
voidwalker sacrificing every time i tell it to attack 

### ISSUE THREAD

**Issue by herbalemu** [elysium-project/server#1104] opened 2017-06-19 02:13 UTC
I have tied clicking the attack button as well as ctrl +1 and it moves a little bit and then sacrifices and I gain the shield. Lvl 21 warlock on alliance.

**Comment by StafordDev** [comment] 2017-06-19 10:39
Try turning off the autocast on Sacrifice. Lvl 29 warlock on alliance, has no problems with that.

**Comment by thepparker** [comment] 2017-08-07 09:33
Cannot reproduce, closing pending further info

**Closed by thepparker** 2017-08-07 09:33 UTC
