### ISSUE TITLE
Commander Gor'shack quest 

### ISSUE THREAD

**Issue by ciacscott** [elysium-project/server#831] opened 2017-05-23 21:46 UTC
I can't pick up the Commander Gor'shack quest even though i have completed the pre-requisites for the quest. 

can someone help me here?

**Comment by TNadal** [comment] 2017-05-23 22:00
did disharmony of flame, commander gor'shack quest is currently available and working (on darrowshire)

![gorsh](https://cloud.githubusercontent.com/assets/15307219/26378227/a0367d06-3fe1-11e7-8284-81e7375a98e6.png)

**Comment by ciacscott** [comment] 2017-05-23 22:22
I did Disharmony of flame (currently on Disharmony of Fire) and all that Galamav the Marksman will give me is "The Pack Mistress".  I am on Darrowshire also

**Comment by GuybrushGit** [comment] 2017-05-24 09:42
Too low level maybe?

**Comment by thepparker** [comment] 2017-08-07 09:14
Quest is currently available as intended, closing pending further information

**Closed by thepparker** 2017-08-07 09:14 UTC
