### ISSUE TITLE
Noggenfogger Elixir

### ISSUE THREAD

**Issue by Bobanhanzz** [elysium-project/server#640] opened 2017-05-08 14:05 UTC
I can't buy Noggenfogger Elixir from "Marin Noggenfogger". I have done the questline for it.

**Comment by Phoosy** [comment] 2017-05-08 14:11
Duplicate of https://github.com/elysium-project/server/issues/548, please use the search function.

**Comment by ImperfectCell** [comment] 2017-05-15 15:51
I also hope noggenfogger can be purged. It technically should be purgable.

**Comment by thepparker** [comment] 2017-08-07 08:08
Was temporarily removed while transforms were bugged

**Closed** 2017-08-07 08:07 UTC
