### ISSUE TITLE
issue with item , what color is

### ISSUE THREAD

**Issue by Tsykihige** [elysium-project/server#1673] opened 2017-07-23 14:19 UTC
Hello i have a problem.
i craft item Dawn Treaders
the problem is this feet is empty, on data base its rare and has stat.
here in game its empty and epic.

http://db.vanillagaming.org/?item=19052

**Comment by luigimannoni** [comment] 2017-07-23 15:52
Duplicate of #1591

**Closed** 2017-07-27 11:42 UTC
Labels: duplicate
