### ISSUE TITLE
Cannot give in finished quests

### ISSUE THREAD

**Issue by planttoucher** [elysium-project/server#1733] opened 2017-07-25 20:31 UTC
Placed some quest items in the bank, later took them back and tried to complete the quests but quest givers had silver question mark instead of yellow and would not accept them. Happened to 4 different quests. Please fix, those sunfish took ages to collect!! 
![wowscrnshot_072517_212406](https://user-images.githubusercontent.com/30447121/28592211-27b9b9ee-7180-11e7-90bc-ffb2f437a1c7.jpg)

**Comment by Phoosy** [comment] 2017-07-25 20:34
Sell the items and buy them back. 
(Github is not a place for personal assistance. Use in-game tickets or the forums to get assistance with bugs).

**Comment by SpaceVector** [comment] 2017-07-26 11:25
I thought this was fixed by this (old) commit ? https://github.com/elysium-project/server/pull/287 @WobLight

**Comment by WobLight** [comment] 2017-07-26 12:11
Maybe another commit caused regression?

**Comment by WobLight** [comment] 2017-07-26 17:49
I'm not able to reproduce it :/

**Closed** 2017-08-08 05:54 UTC
