### ISSUE TITLE
Quest: The tome of valor

### ISSUE THREAD

**Issue by ShootingAir** [elysium-project/server#3281] opened 2017-11-28 18:13 UTC
Hi, have an issue with the quest The tome of valor, I erase by mistake the tome before taking the quest and now Duthorian Rall does not give me another tome, only gives me the tome of the divinity and that mission is already done.

Thanks for the help, my in game name is Taell.

**Comment by Navashed** [comment] 2017-11-29 00:34
Reproduced.

Quest 1793 - The Tome of Valor (0) is not repeatable. This is likely the issue.
If Item 6776 - Tome of Valor is destroyed before Quest 1649 - Tome of Valor (1) is accepted, then Quest 1649 cannot be obtained and its quest chain cannot be completed.

**Comment by Navashed** [comment] 2017-11-30 19:43
Confirmed and added to the new bug tracker: https://github.com/elysium-project/bug-tracker/issues/107

**Comment by Terranzin** [comment] 2017-11-30 21:02
Closing this one since we have a new created issue.

**Closed by Terranzin** 2017-11-30 21:02 UTC

**Comment by ramses241q** [comment] 2017-12-03 00:46
Hi, My character Insanepollo failed a paladin quest named Tome of Valor, i tried to re-aquire but it wouldn't show up, even if i tried to click on the tome in my inventory it said i already had the quest after abandoning it, i contacted a gm and he told me to delete the wdb file but after doing that it still didn't work, it's only showing me a lvl 12 quest named tome of divinity.
