### ISSUE TITLE
Darrowshire: [Plans: Dark Iron Boots] unavailable

### ISSUE THREAD

**Issue by nobomehl** [elysium-project/server#1069] opened 2017-06-14 06:08 UTC
I finally got exalted at Thorium Brotherhood on my warrior (armorsmith) on Darrowshire and can't buy "Plans: Dark Iron Boots" from Lokhtos Darkbargainer in BRD. I found an old forum post for anathema where you forgot to implement the plans too and fixed it..

 Bugged Behavior

[Plans: Dark Iron Boots] are unavailable to purchase from Lokhtos Darkbargainer for Armorsmiths that have Exalted reputation with the Thorium Brotherhood.

 Correct Behavior

[Plans: Dark Iron Boots] should be available to purchase from Lokhtos Darkbargainer for Exalted Thorium Brotherhood Armorsmith's since Patch 1.7.

**Comment by m-laniakea** [comment] 2017-06-14 21:24
Duplicate of https://github.com/elysium-project/server/issues/87

**Closed by m-laniakea** 2017-06-14 21:24 UTC
