### ISSUE TITLE
Bug item - Scouting Tunic of Quality and Rigid bracelets of quality - dont work

### ISSUE THREAD

**Issue by Towarese** [elysium-project/server#2676] opened 2017-09-21 16:29 UTC
Hello,

I want repport a bug :

"Scouting Tunic of Quality +7 damage" and "Rigid bracelets of quality +3 damage" don't work.

"Magician Staff of Quality +7 damage " is work.

Can you repar this bug?

Thank,

Towarese.

**Comment by lovemonkeyz** [comment] 2017-09-22 12:30
Nice reporting, the issue is, "Of Quality" is not a suffix that should exist, and if it does exist on this server, that is the bug, not the fact that you don't get feral +dmg from it.

http://web.archive.org/web/20051227202634/http://www.thottbot.com:80/?s=Magician

http://vanilla-wow.wikia.com/wiki/Item_suffix

http://wowwiki.wikia.com/wiki/Random_item_property

**Comment by Towarese** [comment] 2017-09-22 15:49
You must use the good database...all your link are wrong ....

Stave :
https://db.rising-gods.de/?item=2077

Chest : 
https://db.rising-gods.de/?item=6584

Bracer :
https://db.rising-gods.de/?item=15112

Elysium staff can resolve the bug?

Thank 

Towarese.

**Comment by Phoosy** [comment] 2017-09-22 16:59
Another project's database doesn't not qualify for a "good database" moniker. Here's an actual historical article detailing the possible values of the random property rolls for items on October 18, 2006:

http://wowwiki.wikia.com/wiki/Item_suffix?oldid=288997

Note the complete lack any "of Quality" value. If we even jump forward to nearly WotLK's release there still is no entry about it: http://wowwiki.wikia.com/wiki/Item_suffix?oldid=1612570

These items may as well be custom as far as the Project is concerned at this time.

**Comment by lovemonkeyz** [comment] 2017-09-22 18:13
I love that he used a different private servers DB as proof 👍

**Comment by Towarese** [comment] 2017-09-22 18:21
Please stop comment for nothing or trolling, your wrong ! Not my fault ! Wikia is not the database of elysium. Enjoy wake up :+1: 

Now i only want comment / resolve from real GM. Thank !

**Comment by Phoosy** [comment] 2017-09-22 19:55
The Elysium DB is attempting to emulate a Blizzlike progression of items being implemented for Vanilla WoW (at this current time). Another project's database is not relevant by your own statement. Us stating the facts about the situation is not trolling just because you fail to understand the problem. If you can demonstrate that "of Quality" is a valid item property for randomly rolled attributes, please demonstrate your valid evidence of such.

**Comment by Towarese** [comment] 2017-09-22 20:17
What is your name on ely server? my name is towarese, only check my stuff for understand roll attribute...this is real...

**Comment by Towarese** [comment] 2017-09-22 20:19
exist axe +4 damage lvl 28-29 if i remember and gun lvl 39 +5 damage :)

**Comment by Towarese** [comment] 2017-09-22 20:21
And the question is not exist or not...they exist.

The question is why bracer and chest are bugged and not stave, axe or gun :)

**Comment by lovemonkeyz** [comment] 2017-09-22 20:21
What we are saying is: Elysium is supposed to be 100% blizzlike when it comes to items, the item suffix "Of Quality" did not and has never existed in retail Wow, and should therefor not exist on this realm. Basically, you have reported an item that shouldn't exist not working properly, we're saying the response to this is that they should be removed from the server DB.

**Comment by Towarese** [comment] 2017-09-22 20:26
just check my stuff and you understand you are wrong^^

**Comment by lovemonkeyz** [comment] 2017-09-22 20:27
Holy fuck you are dense. I give up, I'll let a dev come and explain it to you.

**Comment by Towarese** [comment] 2017-09-22 20:31
https://forum.elysium-project.org/topic/34642-items-of-quality-bis-bugged/

Peace !

**Comment by Towarese** [comment] 2017-09-22 20:33
How i can explain this for you and your friend...maybe you never play wow at the start...probly :(

**Comment by Towarese** [comment] 2017-09-22 20:35
So stop trolling with your wrong mind...

i just ask GM for resolve bug with chest and bracer.

Stop kidding troll gnanagnagna "they dont exist" or "not in db"..wtf

**Comment by lovemonkeyz** [comment] 2017-09-22 20:42
Ok, so I'll try and explain this again, in simple english that you may even understand:

The suffix "Of Quality" did not exist in Vanilla. Yes, you have them on you on this server, but that is a bug. The bug is not that they do not work, the bug is that they exist in the elysium database. 

Let me quote from that thread you linked:


> I can't believe people thought of quality items existed in Vanilla lol.

> Of Quality items did not exist, however, stuff like Might of Cenarius  existed back then. This ring has to affect +damage in cat/bearform. I guess we'll see if it works correctly next patch.

>Also i don't remember seeing "of quality" items at all. Ever. Are there any chances that its simply mangos thing?

So, we're not refuting the fact that you have the items on you on this server. We're stating that the bug you want fixed will not be fixed, but the actual fix of this bug is having items with "Of Quality" suffix removed entirely.

**Comment by Towarese** [comment] 2017-09-22 20:47
So why they are in db elysium ? if dont real exist lol? impossible :)

**Comment by lovemonkeyz** [comment] 2017-09-22 20:53
Because Elysium used MangosCore which likely has the item suffix in its DB, but that doesn't mean it existed in vanilla wow, it simply means someone forgot to remove it here. Elysium should be blizzlike, which means the item suffix will be removed. I apologise that your grasp of the english language makes you think I'm "trolling" you. I'm only explaining that the specific bug you're reporting and wanting fixed will not be fixed in the way you had hoped.

**Comment by Towarese** [comment] 2017-09-23 09:28
Maybe but actually they are in game^^

And  player used a lot of gold for buy those item :)  if the staff dont want item of quality, they probly reduce drop rate at 0% but can't delete item with "quality"

For information i see gun lvl 39 +5damage for 500g (horde ah) and someone buy it ...
If i compare with me i need more 1 year for farm 500g xD

Now we must do with....

**Closed** 2017-10-01 04:40 UTC

**Comment by thepparker** [comment] 2017-10-01 04:41
"Quality" items should not exist, and will no longer be available to drop in the near future. Existing items will keep their rolls.
