### ISSUE TITLE
Overall distance issue

### ISSUE THREAD

**Issue by Valkirie** [elysium-project/server#552] opened 2017-04-29 20:13 UTC
**Using latest dev. core I'm having overall distance issue:**

- Often getting "to far away" message when in melee (while untrue).
- Fleeing NPCs once killed will keep running a bit, then, can't be looted.

**Comment by Whyy0416** [comment] 2017-04-30 11:19
same as 3.
If a mob dead before move next to you, or move to next move point, the corpse still move next to you or to next move point. If the corpse stop from a little bit far from where it dead, the corpse can't be loot.
And I noticed mobs usually cast a spell for twice.

**Comment by Valkirie** [comment] 2017-04-30 11:21
@Whyy0416 I think this those problems are linked together with some broken distance calculation on the core. Are they related to vmaps/mmaps/maps ? ..

**Comment by vilkylenth** [comment] 2017-04-30 11:51
I also encountered this problem, I think it's a problem with the mmaps/vmaps/maps， has been unable to find a good mapextractor.

**Comment by brotalnia** [comment] 2017-04-30 14:00
From my testing, it seems to be a recently introduced bug, and it has nothing to do with mmaps. I tested on a month old build and the issue is not present. Upon replacing mangosd.exe with the newest one, the issue appears. I used the same maps/vmaps/mmaps with both, so it has to be a core issue.

An easy way to reproduce this bug is with a warlock. Start casting a ranged spell on a mob, and then send your voidwalker to attack it with the taunt on auto cast. You will pull the mob with your spell, and then as he starts running towards you the pet will taunt him, but the mob will continue running towards you. Your pet will stop running when he taunts the mob and proceed to auto attack as if the mob was next to him, but on your screen the mob will be standing next to your character, instead of where the void taunted him.

Here is a video of the bug - https://www.youtube.com/watch?v=mD9nFugpe1s

**Comment by Whyy0416** [comment] 2017-04-30 14:00
I'm not sure. But I think it's not related to maps/vmaps/mmaps. Feels like related to map update thread or something. I set all per-map threads to 1, but this issue still happen. 
This server seems force enable mmaps, so can't test this without mmaps.
But I think it's more likely related to the code.

**Comment by Fiver** [comment] 2017-05-01 02:12
commit https://github.com/elysium-project/server/commit/9a701a5c04be197c31863fd6d4d84a1a540894f2 cause this bug,revert it will be ok

**Comment by Valkirie** [comment] 2017-05-01 08:00
@Fiver, did a rollback on all changes induced by this commit, problems remains the same.

**Comment by vilkylenth** [comment] 2017-05-01 08:31
@Valkirie  My test results are the same。

**Comment by Whyy0416** [comment] 2017-05-01 10:56
I confirmed that #454 cause this issue. It makes GetTypeId() != TYPEID_PLAYER don't execute int.Launch().
And I noticed branch origin/qa_staging turned void SetTransport(Transport * t) to virtual void, cause I'm not good at code, I can't tell the different between those.
So because I'm not good at code, I can figure out where is the problem ,but I can't fix it. I'm afraid of my fix could cause more bug :(
Best regards.

**Comment by thepparker** [comment] 2017-05-01 19:47
I'll take a look. NPC movement should still be sent, but the spline probably should be interrupted as well

**Comment by thepparker** [comment] 2017-05-01 21:08
I have a fix for creature splines not being interrupted which should rectify moving corpses and creatures appearing to cast while moving, as well a fix for another player teleporting case but I still need to do some testing. 

Not sure what the go is with hunter traps - might be related to not actually knowing where the unit is.

Right now I need to sleep, so I'll PR it a bit later.

**Comment by Valkirie** [comment] 2017-05-02 05:55
@thepparker Thanks. I edited my first post as hunter traps was in fact related to bad player phasing in the world. Only NPC distance and movement bug is still alive.

**Comment by Whyy0416** [comment] 2017-05-02 10:05
@Valkirie I tried to roll back before #454 ,and rebuild_all in visual studio, this problems has solved. And the hunter's traps works fine right?
@thepparker about hunter's trap, I have transport my other characters from mangoszero to this server, the hunter's trap with old character is not work, but the character create with this server, the hunter's trap works fine.
So here is my test result:
![noname](https://cloud.githubusercontent.com/assets/16621446/25613701/c3f33c06-2f61-11e7-92cb-c750aa13d66e.jpg)

**Comment by Valkirie** [comment] 2017-05-02 11:47
@Whyy0416 OK, so let's wait for an official patch from Elysium team regarding #454 induced bugs.
Your problem with imported characters come from the last characters "world_phase_mask" value (has to be 1).

**Comment by StadenElysium** [comment] 2017-05-02 14:42
#454 is not live, so there are issues elsewhere. I'll be finding the commit responsible when I get a moment.

**Comment by Valkirie** [comment] 2017-05-02 14:55
@StadenElysium, I might have forget to say I'm using dev branche. So I guess #454 is live on dev branche right ?

**Comment by thepparker** [comment] 2017-05-02 15:01
Yea the issue was entirely contained in the dev branch

**Comment by blekkulf** [comment] 2017-05-07 10:01
Any updates on this bug? :O

**Comment by vilkylenth** [comment] 2017-05-07 12:41
the problem of  Ranged mobs cann't be loot still exists.

**Comment by thepparker** [comment] 2017-05-07 13:01
The fix has not been merged yet

**Comment by vilkylenth** [comment] 2017-05-07 13:38
@thepparker https://youtu.be/ut-uRVwrXyw  my test.

**Comment by QAkvastskaft** [comment] 2017-10-04 17:17
Fixed before being put on live realm thank you for the report.

**Closed by QAkvastskaft** 2017-10-04 17:17 UTC
Labels: Bug, Fix Needs QA, In Progress
