### ISSUE TITLE
Elysium [Spell] Mind Flay tick missing

### ISSUE THREAD

**Issue by darbai** [elysium-project/server#1637] opened 2017-07-21 21:41 UTC
Third mind flay tick is sometimes missing. When the last tick is missing, it also feel like the first tick is offset by a half second, that is, the spell takes longer to start dealing damage. My hypothesis is that the first tick is sometimes offset, which makes the channeling duration to run out before the last tick as a chance to pop.

This has been tested on both rank 2 and rank 3 of the spell. Roughly 50% of the casts are missing a tick. No macro or addon was used during tests. There were no resists. The ticks did not show up in either combat log or combat text.

Mind flay is an important spell for priests, and having this damage reduction severely impact our gameplay.

**Comment by luigimannoni** [comment] 2017-07-22 12:57
Duplicate of #1614

**Closed** 2017-08-08 05:38 UTC
