### ISSUE TITLE
Shadowcraft Boots Bugged (Zekthur)

### ISSUE THREAD

**Issue by shrogueman** [elysium-project/server#636] opened 2017-05-07 06:41 UTC
Hello,

Shadowcraft boots seem to only be giving +3 atk power to a rogue so I am assuming that is is only giving +3 agility instead of the +21 agility originally intended.

Thanks

- Shrogue

**Comment by Phoosy** [comment] 2017-05-08 14:11
Duplicate of https://github.com/elysium-project/server/issues/548, please use the search function.

**Comment by shrogueman** [comment] 2017-05-08 19:22
Sorry. First time using github

**Comment by m-laniakea** [comment] 2017-05-08 21:56
Duplicate.

**Closed by m-laniakea** 2017-05-08 21:56 UTC
