### ISSUE TITLE
Quest items do not autoloot via shift-rightclick [Zeth/Elysium]

### ISSUE THREAD

**Issue by Unknown-as-Captain** [elysium-project/server#82] opened 2017-03-21 05:46 UTC
When shift-rightclicking a container or mob to loot items, regular items are all picked up as expected, but quest items are not. You must click the item from the loot window to loot it.
This doesn't happen with ALL quest items but it's certainly very noticeable during active play. I am unable to tell why some quest items can be looted like this and some can't.

**This bug did not exist until approx. 2 days ago (around 19/03), it must have been caused by a recent update.**

To reproduce: Kill mobs for quest items, shift+rightclick. Confirm looting of all regular items/vendor trash, but certain quest items remain on the mob. Off the top of my head I am able to confirm this bug with http://db.vanillagaming.org/?item=5056 (objective of http://db.vanillagaming.org/?quest=866) and http://db.vanillagaming.org/?item=14544 (objective of http://db.vanillagaming.org/?quest=5726). More examples can easily be found and added.

**Comment by nikolay510** [comment] 2017-03-21 11:22
Can confirm, happened to me not that long ago with objective http://db.vanillagaming.org/?quest=1708

**Comment by shmgiy429** [comment] 2017-03-21 16:21
I thought I was going insane honestly... This happens for almost every quest item for me; thought it was addon related; most recently http://db.vanillagaming.org/?item=17684 (objective of http://db.vanillagaming.org/?quest=7028)

**Comment by henkethebenke** [comment] 2017-03-21 18:17
Got the same problem. Shift-clicking loots all items except the quest items.

**Comment by FractalCabush** [comment] 2017-03-21 23:52
I am currently looking in to this bug, so far my investigation has pointed me to a possible location for this issue. I will update with any future findings.

**Comment by Unknown-as-Captain** [comment] 2017-03-21 23:55
Thank you very much for looking into it!

**Comment by FractalCabush** [comment] 2017-03-22 10:15
My initial investigation revealed that the problem is not reproducible on the latest development branch of the project. I have debugged and attached listeners for the handlers that deal with loot and ran through it several times looking at shift looting and what happens. 

Quest items are shift lootable in development but not on the live branch. Currently the only way it can fail like that is if the player can store the item but failed to actually store it. That could explain why certain quest items can be shift looted but others can not.

Its a bit tricky to proceed with my investigation since clearly what is live on the servers does not reflect what i have before me in my local development project.

**Comment by FractalCabush** [comment] 2017-03-23 05:11
See https://github.com/elysium-project/server/pull/102 for more information and the possible fix :)

**Comment by shnibble** [comment] 2017-03-23 14:01
FYI this seems to be fixed on live. Yesterday I noticed the bug when looting a particular mob and today I looted the same item from the same mob with shift+right click and it worked as expected.

**Comment by shmgiy429** [comment] 2017-03-23 14:12
Still not fixed on live 100% for sure, I had quest item [Laden Dew Gland](http://db.vanillagaming.org/?item=8428) Shift Auto Loot just fine then I moved on to collecting [Gahz'ridian Oranaments](http://db.vanillagaming.org/?item=8443) and Shift loot does not work on these. On a similar note did Shift looting clams work at some point as well too, cause that hasn't worked for me in a long time.

**Comment by shnibble** [comment] 2017-03-23 14:25
As in opening them to get the contents of clams? That has never worked with auto-loot for me as well. Not sure if that is intentional or not though.

**Comment by FractalCabush** [comment] 2017-03-23 18:08
Well since Claes are containers with items inside, the seem to display the same bug as in shift looting from a gameobject

**Comment by FractalCabush** [comment] 2017-03-27 02:25
It seems as if shift-looting from corpses works fine UNLESS you are in a party because then shift looting quest items no longer works. Im still investigating this bug and im looking around for other developers to help out.

**Comment by shnibble** [comment] 2017-03-27 05:29
Ok yes, being in a party does seem to be the culprit. Noticed the bug again while in a group.

**Comment by shmgiy429** [comment] 2017-03-27 17:34
Yup, definitely a group related thing; 

>  Im still investigating this bug and im looking around for other developers to help out.

What are you looking for here, do you have a section of code/file you think could be the culprit?

**Comment by Unknown-as-Captain** [comment] 2017-03-31 15:21
It seems being in a party is the cause for looting from mobs, but it still happens randomly-ish when looting from objects, such as: http://db.vanillagaming.org/?item=5056 (objective of http://db.vanillagaming.org/?quest=866)

**Closed** 2017-04-03 20:12 UTC
