### ISSUE TITLE
Shadowcraft boots: wrong stats (Zeth'Kur)

### ISSUE THREAD

**Issue by Mnmliq** [elysium-project/server#639] opened 2017-05-08 10:09 UTC
I tried to delete WOW+all Addons(including settings) and etc. Shadowcraft boots are still broken(+3 agility and +9 stamina) . Correct stats: +21 agility and +9 stamina

**Comment by Phoosy** [comment] 2017-05-08 14:13
Duplicate of https://github.com/elysium-project/server/issues/548, please use the search function.

**Comment by Mnmliq** [comment] 2017-05-08 17:33
#548 :  u just tell the same and add tag "confirmed", i dont understand what this mean. I have spoken with gm, we tried to fix my boots by resending them to me (same "wrong" stats)..then GM told me to report bugg here and said "bye" to me

**Comment by m-laniakea** [comment] 2017-05-08 17:47
Duplicate

**Closed by m-laniakea** 2017-05-08 17:47 UTC
