### ISSUE TITLE
Dark Rune

### ISSUE THREAD

**Issue by Tharim** [elysium-project/server#1391] opened 2017-07-07 13:48 UTC
Did 2 Scholomance runs after the fixes on the 5th of July and I didn't get any Dark Rune drops at all. Also have multiple reports from people in my guild with the same issue. Could you please check if they are still in the loot table at all?

**Comment by JosipbrozElysium** [comment] 2017-07-07 14:34
Duplicate of #1369 !

**Closed by JosipbrozElysium** 2017-07-07 14:34 UTC
