### ISSUE TITLE
Blackwood Totemic's Healing Ward is attacking with melee hits.

### ISSUE THREAD

**Issue by Cabro** [elysium-project/server#2609] opened 2017-09-17 07:07 UTC
This is basically a totem, it should only heal the NPC that spawned it and the otehr friendly NPCs in range. It should not attack with melee swings, lol.

**Comment by brotalnia** [comment] 2017-09-17 19:28
Confirmed. The issue is here: https://github.com/elysium-project/server/blob/3b30d391ec5f6f528462611a3f789126c500c166/src/scripts/eastern_kingdoms/stranglethorn_vale/zulgurub/boss_jindo.cpp#L322 

I don't know why this even has a core script. It should be done with TotemAI.

**Comment by brotalnia** [comment] 2017-09-29 15:06
Fixed in https://github.com/elysium-project/server/commit/9f340cdd971ffc202a34ddac27ea9e36d0d53b40

**Closed by brotalnia** 2017-09-29 15:06 UTC
Labels: QA Confirmed Issue
