### ISSUE TITLE
[Elysium PvP] NPC Legacki is lost in WS

### ISSUE THREAD

**Issue by Damienrantoanison** [elysium-project/server#2594] opened 2017-09-16 11:00 UTC
Hello Dev team :)

The NPC Legacki is lost near Everlook, I don't have the exact position but see the screenshot below.

![capture d ecran 2017-09-16 12 51 54](https://user-images.githubusercontent.com/5601685/30511702-e601acea-9ade-11e7-8231-36ae8d204555.png)

**Comment by lovemonkeyz** [comment] 2017-09-16 11:04
Likely a bug caused by the "Are we there, Yeti?" quest to scare her

**Comment by Damienrantoanison** [comment] 2017-09-16 11:07
Yes i think so, but she went way too far and now she's stuck here in middle of nowhere.

**Comment by BrynjaDarrow** [comment] 2017-09-16 12:39
This issue has already been fixed, but was not yet implemented on Darrowshire & Elysium.

https://github.com/elysium-project/server/pull/2400

**Comment by brotalnia** [comment] 2017-09-16 14:23
What Brynja said. Duplicate of https://github.com/elysium-project/server/issues/2389 and already fixed.

**Closed by brotalnia** 2017-09-16 14:23 UTC
Labels: duplicate
