### ISSUE TITLE
Southsea mobs in lost rigger cove

### ISSUE THREAD

**Issue by aznmark** [elysium-project/server#3264] opened 2017-11-15 16:05 UTC
The bridge leading towards the two ships in tanaris lost rigger cove doesn't seem to be effected by my cone of cold damage. Rest of my spells like frost nova and blizzard are hitting them. I don't know if the bridge is bugged and if its a vanilla thing. Thanks

**Comment by Terranzin** [comment] 2017-11-15 19:08
Hello,

Thanks for your report. I´ve now reviewed your issue and I cant reproduce the error you´re facing. I attempted using Cone of cold on all 4 bridges between the two ships. 

![image](https://user-images.githubusercontent.com/25831382/32854938-873d5dc6-ca40-11e7-8432-197b216655c3.png)

For now we´re closing the issue, if you manage to reproduce it, please provide a screenshot.

**Closed** 2017-11-15 19:09 UTC

**Comment by aznmark** [comment] 2017-11-16 05:35
Not that. Sorry. Kind of worded "bridge" wrong. But the flat entrance path leading towards the first ship.

**Comment by Terranzin** [comment] 2017-11-16 20:28
Greetings, I´ll keep this one closed. I´m doing a new review of this matter on our new bug-tracker https://github.com/elysium-project/bug-tracker/issues/49
