### ISSUE TITLE
Deadmines Parrots bugged

### ISSUE THREAD

**Issue by Kuuppax** [elysium-project/server#201] opened 2017-03-29 19:26 UTC
If you right click a NPC with a parrot, matter how far away it is, the parrot charges you and when it attacks you it pulls the NPC as well and the NPC pulls every single other NPC on the way to you.

I'm not actually even sure, do I want this bug fixed cuz it's so Leeeroy Jenkins that it's almost cool, at least it's enjoyable when you want to wipe the group in a cool way on purpose.

**Comment by AndersSahlin** [comment] 2017-03-30 18:49
Duplicate of #106.

**Closed** 2017-04-02 07:54 UTC
