### ISSUE TITLE
BRD Strong Lock Boxes loot

### ISSUE THREAD

**Issue by polischuk16** [elysium-project/server#1654] opened 2017-07-22 16:57 UTC
I understand that the loot has been nurfed due to gold seller or whatever, but come on, rogues need to farm gold and that was one of the best ways to do it. Its completely unfair because mages can still farm DMN and make even more gold that rogues ever could, nurf that as well then or fix the loot and make it blizzlike.

**Comment by luigimannoni** [comment] 2017-07-22 17:34
Duplicate of #1553 #1348 and #1399

**Closed** 2017-08-08 05:36 UTC
