### ISSUE TITLE
Dawn Treaders have bugged itemization on Elysium

### ISSUE THREAD

**Issue by insearchofthe** [elysium-project/server#1703] opened 2017-07-24 19:02 UTC
Dawn Treaders, a Leatherworking crafted item added with the Patch 1.6 with the Argent Dawn rep reward additions, currently appear as Epic boots with no stats. The stats should be as follows:

http://db.vanillagaming.org/?item=19052

http://wowwiki.wikia.com/wiki/Dawn_Treaders - Added in Patch 1.6 along with http://wowwiki.wikia.com/wiki/Golden_Mantle_of_the_Dawn (which is currently stat'd properly).

**Comment by luigimannoni** [comment] 2017-07-24 20:07
Duplicate of #1591

**Comment by ShortBusSubsidiary** [comment] 2017-07-29 02:13
Any update on these?

**Comment by Razorwynd** [comment] 2017-08-04 20:17
.. actually decent boots for druid tank

**Comment by thepparker** [comment] 2017-08-08 05:42
Duplicate

**Closed by thepparker** 2017-08-08 05:42 UTC
